force-app/main/default/objects/Album__c/Album__c.object-meta.xml
<CustomObject>
    <description>An object to store artist&#39;s albums or EPs</description>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Album__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <label>Artist</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Albums</relationshipLabel>
    <relationshipName>Albums</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Album__c/fields/Cover__c.field-meta.xml
<CustomField>
    <fullName>Cover__c</fullName>
    <label>Cover</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Album__c/fields/Release_Year__c.field-meta.xml
<CustomField>
    <fullName>Release_Year__c</fullName>
    <label>Release Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_pic__c.field-meta.xml
<CustomField>
    <fullName>Profile_pic__c</fullName>
    <label>Profile pic</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Artist.recordType-meta.xml
<RecordType>
    <fullName>Artist</fullName>
    <active>true</active>
    <description>This record type is used to store an artist&#39;s info. It includes personal, account-related and music-related information.</description>
    <label>Artist</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/User.recordType-meta.xml
<RecordType>
    <fullName>User</fullName>
    <active>true</active>
    <description>This record type is used to store a user&#39;s info. It contains personal and account-related information.</description>
    <label>User</label>
</RecordType>

force-app/main/default/classes/artistCatalogController.cls
public class artistCatalogController {
       
    @TestVisible
    static String sanitizeQueryString(String aQuery) {
        if (aQuery == null){
            return '%';
        }
        String trimmedQuery = aQuery.trim();
        if (trimmedQuery.length() == 0){
            return '%';
        }
        return '%' + trimmedQuery.replaceAll('\\W+', '%') + '%';
    }
    
    @AuraEnabled
    public static List<Contact> allArtists(String nameFilterString) {
        String composedFilter = sanitizeQueryString(nameFilterString);
        return [SELECT Name,Id,Profile_pic__c FROM Contact WHERE Name LIKE :composedFilter AND RecordType.Name='Artist'];
    } 
    
        @AuraEnabled
    public static List<Contact> allUsers(String nameFilterUsers) {
         String composedFilter = sanitizeQueryString(nameFilterUsers);
        return [SELECT Name,Id,Profile_pic__c,Email FROM Contact WHERE Name LIKE :composedFilter AND RecordType.Name='User'];
    } 
    
    
    @AuraEnabled
    public static List<Contact> getAlbumList(String artistID){ 
        return [SELECT (SELECT Id, Name, Description__c,Cover__c,Release_Year__c FROM Albums__r) FROM Contact WHERE Id=:artistID];
    }
    
    @AuraEnabled
    public static List<Album__c> getSongList(String albumID){ 
        return [SELECT (SELECT Name, Duration__c FROM Songs__r) FROM Album__c WHERE Id=:albumID];
    }

    
}