force-app/main/default/objects/Album__c/Album__c.object-meta.xml
<CustomObject>
    <description>An object to store artist&#39;s albums or EPs</description>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Album__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <label>Artist</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Albums</relationshipLabel>
    <relationshipName>Albums</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Artist.recordType-meta.xml
<RecordType>
    <fullName>Artist</fullName>
    <active>true</active>
    <description>This record type is used to store an artist&#39;s info. It includes personal, account-related and music-related information.</description>
    <label>Artist</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/User.recordType-meta.xml
<RecordType>
    <fullName>User</fullName>
    <active>true</active>
    <description>This record type is used to store a user&#39;s info. It contains personal and account-related information.</description>
    <label>User</label>
</RecordType>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <formula>Album__r.Artist__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Artist</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/artistCatalogTest.cls
@isTest
public class artistCatalogTest {
    @isTest
    static void testQueryString(){
        String res = artistCatalogController.sanitizeQueryString(null);
        System.assertEquals('%', res);
        
        String emptyRes = artistCatalogController.sanitizeQueryString(' ');
        System.assertEquals('%', emptyRes);
        
        String pRes = artistCatalogController.sanitizeQueryString('Im a test');
        System.assertEquals( '%Im%a%test%', pRes);
    }
    
    @isTest
    static void testArtistList(){
        Contact artist = new Contact();
        artist.FirstName = 'test';
        artist.LastName = 'test';
        artist.RecordTypeId = '0121U000000jO3pQAE';
        insert artist;
        
        List<Contact> res = artistCatalogController.allArtists('tes');
        System.assert(res.size()!=0);
    }
    
       @isTest
    static void testUserList(){
        Contact user = new Contact();
        user.LastName = 'test';
        user.RecordTypeId = '0121U000000jO0gQAE';
        insert user;
        
        List<Contact> res = artistCatalogController.allUsers('tes');
        System.assert(res.size()!=0);
    }
    
    @isTest
    static void testAlbumsnadSongs(){
        Contact artist = new Contact();
        artist.LastName = 'test';
        insert artist;
        
        Album__c album = new Album__c();
        album.Name = 'test';
        album.Artist__c=artist.Id;
        insert album;
        
        Song__c song = new Song__c();
        song.Name='test';
        song.Album__c = album.Id;
        insert song;
        
        List<Contact> albums = artistCatalogController.getAlbumList(artist.Id);
        System.assert(albums.size()==1);
        List<Album__c> songs = artistCatalogController.getSongList(album.Id);
        System.assert(songs.size()==1);
    }
    
  
}