force-app/main/default/objects/Account/fields/Active_subscription__c.field-meta.xml
<CustomField>
    <fullName>Active_subscription__c</fullName>
    <formula>TODAY() &lt; (Purchase_date__c + 30)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active subscription</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Expiration_date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_date__c</fullName>
    <description>Calculates the membership&#39;s expiration date (30 days after purchase)</description>
    <formula>Purchase_date__c +30</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiration date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Profile_Pic__c.field-meta.xml
<CustomField>
    <fullName>Profile_Pic__c</fullName>
    <label>Profile Pic</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Purchase_date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_date__c</fullName>
    <description>Date when the user&#39;s membership was activated.</description>
    <label>Purchase date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Album__c/Album__c.object-meta.xml
<CustomObject>
    <description>An object to store artist&#39;s albums or EPs</description>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Album__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <label>Artist</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Albums</relationshipLabel>
    <relationshipName>Albums</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Album__c/fields/Cover__c.field-meta.xml
<CustomField>
    <fullName>Cover__c</fullName>
    <label>Cover</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Album__c/fields/Release_Year__c.field-meta.xml
<CustomField>
    <fullName>Release_Year__c</fullName>
    <label>Release Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_pic__c.field-meta.xml
<CustomField>
    <fullName>Profile_pic__c</fullName>
    <label>Profile pic</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <formula>Album__r.Artist__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Artist</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/homeControler.cls
public class homeControler {
    
    @AuraEnabled
    public static Account getAccount(String password){
        Account acc = new Account();
        try{
            acc = [SELECT Name, Active_subscription__c,Purchase_date__c,Type,Profile_Pic__c,Expiration_date__c,(SELECT Id,Name FROM Contacts) FROM Account WHERE Password__c=:password LIMIT 1];  
        }catch (DmlException e) {
            acc = null;
        }
        
        return acc;
    }
    
    
    @AuraEnabled
    public static Album__c createAlbum(String name, String releaseYear, String description, Id artistID, String cover){
        Album__c newAlbum = new Album__c();
        newAlbum.Name = name;
        newAlbum.Release_Year__c = releaseYear;
        newAlbum.Description__c = description;
        newAlbum.Artist__c = artistID;
        newAlbum.Cover__c = cover;
        
        insert newAlbum;
        
        return newAlbum;
    }
    
    
    @AuraEnabled
    public static Date renewSubscription(String password){
        Account acc = [SELECT Name, Purchase_date__c FROM Account WHERE Password__c=:password LIMIT 1];
        acc.Purchase_date__c = System.today();
        update acc;
        return acc.Purchase_date__c; 
    }
    
    @AuraEnabled
    public static List<Contact> getAlbumList(Id artistID){
        try{
        return [SELECT (SELECT Name FROM Albums__r) FROM Contact WHERE Id=:artistID];
        }catch(DmlException e) {
            return null;
        }
    }
    
        @AuraEnabled
    public static Song__c createSong(String name, String duration, String album){
        Album__c albumId = [SELECT Id FROM Album__c WHERE Name=:album LIMIT 1];
        Song__c newSong = new Song__c();
        newSong.Name = name;
        newSong.Duration__c = duration;
        newSong.Album__c = albumId.Id;
        
        insert newSong;
        
        return newSong;
    }
    
    
}