force-app/main/default/objects/Account/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Profile_Pic__c.field-meta.xml
<CustomField>
    <fullName>Profile_Pic__c</fullName>
    <label>Profile Pic</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Purchase_date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_date__c</fullName>
    <description>Date when the user&#39;s membership was activated.</description>
    <label>Purchase date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_pic__c.field-meta.xml
<CustomField>
    <fullName>Profile_pic__c</fullName>
    <label>Profile pic</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Artist.recordType-meta.xml
<RecordType>
    <fullName>Artist</fullName>
    <active>true</active>
    <description>This record type is used to store an artist&#39;s info. It includes personal, account-related and music-related information.</description>
    <label>Artist</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/User.recordType-meta.xml
<RecordType>
    <fullName>User</fullName>
    <active>true</active>
    <description>This record type is used to store a user&#39;s info. It contains personal and account-related information.</description>
    <label>User</label>
</RecordType>

force-app/main/default/classes/registerControler.cls
public class registerControler {
    
     @AuraEnabled
    public static Account createAccount(String name, String firstName, String lastName, String email,
                                       String phone, String password, String accType, String description, 
                                    String MailingCity, String MailingState, String MailingCountry, String MailingPostalCode, String MailingStreet,String avatar){
        Account account = getAccountInformation(email);
        if(account == null){
            account = CreateAccount(name, email, password, accType, avatar); 
        }
        
        Contact newContact = createContact(account, accType, firstName, lastName, email, phone, description, MailingCity, MailingState, MailingCountry, MailingPostalCode, MailingStreet,avatar);
        return account;
    }
    
    
    public static Account getAccountInformation(String email){
        try{
            Account acc = [SELECT Name FROM Account WHERE Email__c=:email LIMIT 1];
            return acc; 
        } catch(Exception e){}
        return null;
    }
    
    
    public static Account CreateAccount(String name, String email, String password, String accType,String avatar){
        Account newAcc = new Account();
        
        newAcc.Name = name;
        newAcc.Email__c = email;
        newAcc.Password__c = password;
        newAcc.Type = accType;
        newAcc.Purchase_date__c = System.today();
        newAcc.Profile_Pic__c = avatar;
        
        insert newAcc;
        return newAcc;
    }
    
    
    public static Contact createContact(Account acc, String accType, String firstName, String lastName, String email, String phone, String description,
     String MailingCity, String MailingState, String MailingCountry, String MailingPostalCode, String MailingStreet, String avatar){
       Contact newContact = new Contact();
        
        Id userTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('User').getRecordTypeId();
        Id artistTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Artist').getRecordTypeId();
        
        newContact.AccountId = acc.Id;
        newContact.email = email;
        newContact.Phone = phone; 
        newContact.lastName = lastName;
        newContact.MailingCity = MailingCity;
        newContact.MailingState = MailingState;
        newContact.MailingCountry = MailingCountry;
        newContact.MailingPostalCode = MailingPostalCode;
        newContact.MailingStreet = MailingStreet;
        newContact.Profile_pic__c = avatar;
        
        if(accType=='User'){
            newContact.FirstName = firstName;
            newContact.RecordTypeId = userTypeId;
            
        } else if(accType=='Artist'){
            newContact.Description = description;
            newContact.RecordTypeId = artistTypeId;
        }
        
      insert newContact;
      return null;
    }

}