force-app/main/default/objects/Account/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Purchase_date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_date__c</fullName>
    <description>Date when the user&#39;s membership was activated.</description>
    <label>Purchase date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Album__c/Album__c.object-meta.xml
<CustomObject>
    <description>An object to store artist&#39;s albums or EPs</description>
    <label>Album</label>
    <nameField>
        <label>Album Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Albums</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Album__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <label>Artist</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Albums</relationshipLabel>
    <relationshipName>Albums</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Album__c/fields/Number_of_songs__c.field-meta.xml
<CustomField>
    <fullName>Number_of_songs__c</fullName>
    <description>Calculates the number of songs associated with this album.</description>
    <label>Number of songs</label>
    <summaryForeignKey>Song__c.Album__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <formula>Album__r.Artist__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Artist</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/homeControlerTest.cls
@isTest
public class homeControlerTest {

    @isTest
    static void testGetAccount(){
        Account ac = new Account();
        ac.Name = 'Test';
        ac.Password__c = 'hi';
        insert ac;
        
        Account res = homeControler.getAccount('hi');
        System.assert(res!=null);
        
    }
    
    @isTest
    static void testRenew(){
        Account ac = new Account();
        ac.Name = 'Test';
        ac.Password__c = 'hi';
        ac.Purchase_date__c = Date.newInstance(2016, 12, 9);
        insert ac;
        
        Date res = homeControler.renewSubscription('hi');        
        System.assert(System.today() == res);
    }
    
    @isTest
    static void testCreateAlbum(){
        Contact cont = new Contact();
        cont.LastName = 'Test';
        insert cont;
        
        Album__c res = homeControler.createAlbum('name', '2008', 'description', cont.Id, '');
        List<Album__c> search = [SELECT Name FROM Album__c WHERE Artist__c=:cont.Id];
        System.assertEquals(1, search.size());
    }
    
    @isTest
    static void testGetAlbums(){
        Contact cont = new Contact();
        cont.LastName = 'Test';
        insert cont;
        
        Album__c album= new Album__c();
        album.Name = 'Album';
        album.Artist__c = cont.Id;
        insert album; 
        
        List<Contact> res = homeControler.getAlbumList(cont.Id);
        System.assertEquals(1, res.size());
        
        List<Contact> neg = homeControler.getAlbumList(null);
        System.assertEquals(0, neg.size());
        
    }
    
    @isTest
    static void testCreateSong(){
        Contact cont = new Contact();
        cont.LastName = 'test';
        insert cont; 
        
        Album__c album = new Album__c();
        album.Artist__c = cont.Id;
        album.Name = 'Test';
        insert album;
        
        Song__c song = homeControler.createSong('song','2:13','Test');
        
        List<Album__c> res = [SELECT Number_of_songs__c FROM Album__c WHERE Id=:album.Id];
        System.assertEquals(1, res.size());
    }
}